// Auto-generated by business-agent
const config = {
  name: "FairPay",
  tagline: "Know your worth",
  description: "Get a fair salary range for your skills and experience. Our AI-powered salary predictor uses historical data and market trends to help you negotiate your next job offer.",
  primaryColor: "emerald",
  accentColor: "green",
  features: ["Personalized salary prediction","Market trend analysis","Comparative industry benchmarks"],
  niche: "job-search",
  targetAudience: "job seekers",
  monetization: ["Primary: Affiliate marketing with job boards or career platforms","Secondary: Sponsored content or product placements"],
  seoStrategy: {"keywords":["salary predictor","job search","fair pay","market trends"],"contentStrategy":"Create informative blog posts and guides on salary negotiation and job search best practices"},
};

export default config;
